import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./Component/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className } style={{padding:"10px 80px"}}>
        <Header />
        {children}
      </body>
    </html>
  );
}
